import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import '../core/user_model.dart';

class PdfService {
  /// Generates a personalized health plan PDF
  static Future<File> generateHealthPlan(UserData user, String planType, List<String> exercises) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(40),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('VitaAI Health Plan', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                pw.SizedBox(height: 20),
                pw.Divider(),
                pw.SizedBox(height: 20),
                pw.Text('User Details:', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Text('Name: ${user.name}'),
                pw.Text('Age: ${user.age}'),
                pw.Text('Weight: ${user.weight ?? "N/A"} kg'),
                pw.Text('Height: ${user.height ?? "N/A"} cm'),
                pw.SizedBox(height: 20),
                pw.Text('Nutritional Profile (Daily Targets):', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.Text('• Calcium: 1000 mg'),
                pw.Text('• Protein: 80 g'),
                pw.Text('• Water: 3.5 L'),
                pw.SizedBox(height: 30),
                pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  color: PdfColors.blue100,
                  child: pw.Text('Recommended $planType Plan', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                ),
                pw.SizedBox(height: 10),
                ...exercises.map((e) => pw.Bullet(text: e)),
                pw.Spacer(),
                pw.Divider(),
                pw.Align(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text('Generated by VitaAI Healthcare System', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                ),
              ],
            ),
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/${planType.toLowerCase()}_plan_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  /// Generates a detailed Tax Invoice for consultations
  static Future<File> generateTaxInvoice(UserData user, String specialistName, double amount) async {
    final pdf = pw.Document();

    // Tax Calculations
    final double baseAmount = amount / 1.18; // Assuming 18% GST included
    final double gstAmount = amount - baseAmount;
    final double cgst = gstAmount / 2;
    final double sgst = gstAmount / 2;

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(40),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('VitaAI Healthcare', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                        pw.Text('123 Wellness Ave, Health City', style: const pw.TextStyle(fontSize: 10)),
                        pw.Text('GSTIN: 27AABCU9603R1Z2', style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.end,
                      children: [
                        pw.Text('TAX INVOICE', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                        pw.Text('#INV-${DateTime.now().millisecondsSinceEpoch}', style: const pw.TextStyle(fontSize: 10)),
                        pw.Text('Date: ${DateTime.now().toString().split(' ')[0]}', style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                pw.SizedBox(height: 30),
                pw.Divider(),
                pw.SizedBox(height: 20),

                // Bill To
                pw.Text('Billed To:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text(user.name),
                pw.Text(user.email ?? ''),
                if (user.phone != null) pw.Text(user.phone!),
                pw.SizedBox(height: 30),

                // Line Items
                pw.Container(
                  color: PdfColors.grey200,
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Row(
                    children: [
                      pw.Expanded(flex: 4, child: pw.Text('Description', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Expanded(flex: 2, child: pw.Text('HSN/SAC', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Expanded(flex: 2, child: pw.Text('Amount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                    ],
                  ),
                ),
                pw.Padding(
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Row(
                    children: [
                      pw.Expanded(flex: 4, child: pw.Text('Online Consultation - $specialistName')),
                      pw.Expanded(flex: 2, child: pw.Text('9983')),
                      pw.Expanded(flex: 2, child: pw.Text('₹${baseAmount.toStringAsFixed(2)}')),
                    ],
                  ),
                ),
                pw.Divider(),
                
                // Totals
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.end,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.end,
                      children: [
                        pw.Text('Taxable Amount: ₹${baseAmount.toStringAsFixed(2)}'),
                        pw.Text('CGST (9%): ₹${cgst.toStringAsFixed(2)}'),
                        pw.Text('SGST (9%): ₹${sgst.toStringAsFixed(2)}'),
                        pw.SizedBox(height: 4),
                        pw.Text('Total Amount: ₹${amount.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                      ],
                    ),
                  ],
                ),

                pw.Spacer(),
                pw.Divider(),
                pw.Center(child: pw.Text('This is a computer generated invoice and does not require signature.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))),
                pw.Center(child: pw.Text('Thank you for choosing VitaAI!', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))),
              ],
            ),
          );
        },
      ),
    );

    final output = await getTemporaryDirectory(); // Use temp dir for uploading
    final file = File("${output.path}/invoice_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
